### ISSUE TITLE
Custom file name in relative build paths (Feature request)

### ISSUE THREAD

**Issue by veglar** [inqlik/inqlik-tools#5]
### Feature request
I've started a new project where we are multiple developers using sublime for development pushing and pulling QDF container releases from GIT. 

Our qvw (qvf) files are build up of multiple qvs-files that we include in the script. On top of each qvs file we add the absolute build path.  

```
//#!c:\Dev\Veglar\1.MyContainer\1.Application\TheApplication.qvw   
```
The full path causes trouble when committing , hence each developer have its own development path each developer needs to change the path every time another developer have committed code to the master repoitory,

```
//#!..\..\1.Application\
```
To use relative path the qlikview-application need to be named as the same as the qvs which will not be the case when we are including multiple qvs-files into the same application.

I would love to see an extensioin to the relative buld path to even accept custom qvw-file names. 
```
//#!..\..\1.Application\TheApplication.qvw   
```

*PS: Did you see that Qlik mentioned InQlik tools in their Qlik IDE Development environment document*

**Comment by vadimtsushko** [comment]
Hi Vegar.

I'll look at this as soon as possible, but currently I and my team use different version of InQlik tools, not yet released. It use external command-line tool for many tasks, including reloading and opening QV apps. So I have to consolidate that release firstly, then I will be ready for that fieature request.

**Comment by vadimtsushko** [comment]
Hi Vegar.
I've relased fresh version of plugin and now I believe your scenario is covered.
But you have to switch new `qv_script_use_cli` parameter to true to activate new mechanism.
In future I think it would be activated by default but I prefer to check it some more time.


So recommended steps:

- Upgrade to version of Inqlik-Tools (currently 0.1.38)
- Go to `Pregerences \ Package settings \  Inqlik-Tools \ QlikView script settings: Default` and copy content
- Go to `Pregerences \ Package settings \  Inqlik-Tools \ QlikView script settings: User` and paste content
- Change line   "qv_script_use_cli": false, to   "qv_script_use_cli": true
