### ISSUE TITLE
In v0.1.40 the expressions functionality saves a csv file with <filename>.tables.csv

### ISSUE THREAD

**Issue by alexmosq** [inqlik/inqlik-tools#9]
The .tables. in the name was not there before v0.1.40

**Comment by vadimtsushko** [comment]
Expression Editor supports several output formats. You can switch output format in package settings file: Go to menu

Preferences / Package Settings / InQlik-Tools / QlikView Variables file settings: User

For QlikView Deployment Framework compatible file format it should be set to QDF

Suppoprted formats:

QDF: QlikView Deployment Framework compatible CSV file format

CSV: Free form CSV file format

QVS: QLikVIew load script format

JSON: JSON

**Comment by alexmosq** [comment]
Thanks!
